<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.alibaba.cola.demo.web</groupId>
        <artifactId>demo-web-parent</artifactId>
        <version>1.0.0-SHAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>demo-web-app</artifactId>
    <packaging>jar</packaging>
    <name>demo-web-app</name>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cola.demo.web</groupId>
            <artifactId>demo-web-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cola.demo.web</groupId>
            <artifactId>demo-web-infrastructure</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-catchlog-starter</artifactId>
        </dependency>

<!--        &lt;!&ndash; JSR 303 Validation &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.hibernate.validator</groupId>-->
<!--            <artifactId>hibernate-validator</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>javax.el</groupId>-->
<!--            <artifactId>javax.el-api</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.glassfish</groupId>-->
<!--            <artifactId>jakarta.el</artifactId>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; JSR 303 Validation End&ndash;&gt;-->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
