// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StockService.proto
// Protobuf Java Version: 4.34.1

package com.alibaba.demo.dubbo.grpc.api;

@com.google.protobuf.Generated
public interface GetStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
