// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StockService.proto
// Protobuf Java Version: 4.34.1

package com.alibaba.demo.dubbo.grpc.api;

@com.google.protobuf.Generated
public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 num = 3;</code>
   * @return The num.
   */
  int getNum();

  /**
   * <code>string des = 4;</code>
   * @return The des.
   */
  java.lang.String getDes();
  /**
   * <code>string des = 4;</code>
   * @return The bytes for des.
   */
  com.google.protobuf.ByteString
      getDesBytes();
}
