// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StockService.proto
// Protobuf Java Version: 4.34.1

package com.alibaba.demo.dubbo.grpc.api;

@com.google.protobuf.Generated
public final class StockServiceProto extends com.google.protobuf.GeneratedFile {
  private StockServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "StockServiceProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StockService.proto\"\035\n\017GetStockRequest\022" +
      "\n\n\002id\030\001 \001(\003\"C\n\rStockResponse\022\n\n\002id\030\001 \001(\003" +
      "\022\014\n\004name\030\002 \001(\t\022\013\n\003num\030\003 \001(\005\022\013\n\003des\030\004 \001(\t" +
      "2>\n\014StockService\022.\n\010GetStock\022\020.GetStockR" +
      "equest\032\016.StockResponse\"\000B6\n\037com.alibaba." +
      "demo.dubbo.grpc.apiB\021StockServiceProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetStockRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_GetStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetStockRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_StockResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_StockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StockResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Num", "Des", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
