syntax = "proto3";
option java_package = "com.example.protobuf";
option java_outer_classname = "HelloProto";

enum Cmd{
  UNKNOWN = 0;
  HEARTBEAT = 1;
  LOGIN = 2;
  CHAT = 3;
  CONNECTED = 4;
  MOVE = 5;
}

message MessageWrapper {
  string cmd = 1;
  int64 userId = 2;
  int64 clientId = 3;
  bytes body = 4;
}

message LoginRequest {
  int64 userId = 1;
  string token = 3;
}

message ChatMessage {
  string fromUserId = 1;
  string toUserId = 2;
  string content = 3;
  int64 timestamp = 4;
}

message Heartbeat {
  int64 clientId = 1;
  int64 clientTime = 2;
}

message ServerPeerConnected{
  int64 timestamp = 1;
}

message Move {
  oneof payload {
    MoveReq req = 1;
    MoveResp resp = 2;
  }
}

message MoveReq{
  int32 x = 1;
  int32 y = 2;
}

message MoveResp{
  int64 playerId = 1;
  int32 x = 2;
  int32 y = 3;
}

// 错误消息
message ErrorMsg {
  string error = 1;
}
